Updates and fixes for z platform
ibmruntimes/openj9-openjdk-jdk11 pull request #593
Opened 2022-12-01 13:29 UTC by jpfurminger

- TokenLabel keyword support
- APAR IJ09107
- Point does not match field size Exception for EC curves
- Aliases for ECDSA and ECDH Public Key

Signed-off-by: Jon Furminger furming@us.ibm.com

2022-12-01 13:58 UTC, pshipton commented
Pls fix the Signed-off-by in your commit message. Currently it's `Signed-off-by: Jon Furminger furming@us.ibm.com` but it should be `Signed-off-by: Jon Furminger <furming@us.ibm.com>`

2022-12-01 14:08 UTC, pshipton commented
jenkins test sanity.openjdk jdk11 amac,zlinux

2022-12-01 14:21 UTC, pshipton commented
jenkins test sanity.openjdk amac,zlinux jdk11

2022-12-01 14:38 UTC, pshipton commented
Additional security testing on amac https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1576/

2022-12-01 14:47 UTC, pshipton commented
Started some [internal testing](https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/15004/) as well.

2022-12-01 15:26 UTC, jpfurminger commented
> Pls fix the Signed-off-by in your commit message. Currently it's `Signed-off-by: Jon Furminger furming@us.ibm.com` but it should be `Signed-off-by: Jon Furminger <furming@us.ibm.com>`

Seems to be fixed.

2022-12-05 21:39 UTC, keithc-ca requested changes

2022-12-06 21:55 UTC, pshipton commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/P11ECKeyFactory.java
> +                    point = decodePoint(attributes[0].getByteArray(), params.getCurve());
Addressed via https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/598

2022-12-08 17:34 UTC, keithc-ca commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/P11ECKeyFactory.java
> +                    point = decodePoint(attributes[0].getByteArray(), params.getCurve());
I don't see a comment in https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/598 and the code appears unchanged. Was the comment wrong?

2022-12-08 22:00 UTC, pshipton commented on src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/P11ECKeyFactory.java
> +                    point = decodePoint(attributes[0].getByteArray(), params.getCurve());
It seemed like the comment was wrong. The change is actually a backport of https://github.com/openjdk/jdk/commit/55f5542c, which doesn't contain any comment.

2023-02-07 20:37 UTC, pshipton commented
Closing since this is replaced by https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/598

2023-02-07 20:37 UTC, closed without merging