Allow RestrictedSecurity property extension from default values
ibmruntimes/openj9-openjdk-jdk11 pull request #819
Opened 2024-10-04 15:51 UTC by KostasTsiounis

The default values existing in the java.security file are now considered the baseline and all profiles can inherit them and add or remove to them, if they are in list form. This does not include the providers, though.

Back-ported from: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/849

Signed-off-by: Kostas Tsiounis <kostas.tsiounis@ibm.com>

2024-10-04 15:53 UTC, KostasTsiounis commented
FYI @keithc-ca

2024-10-04 21:01 UTC, keithc-ca requested changes

2024-10-04 22:18 UTC, KostasTsiounis commented on src/java.base/share/conf/security/java.security
> +RestrictedSecurity.OpenJCEPlusFIPS.FIPS140-3.desc.hash = SHA256:bea1b7da967ac27720b7bc439ccd2d4250ebe783a6919a8e7047e6a6b862a116
You are right. The profile is a bit different in 11. I built and run it to make sure. The hash needed is `5757f948a738ca5c9e066655591d511c27d3f2c3ec593c77bf2c17af360a1695`, which is a bit different.

2024-10-04 22:43 UTC, KostasTsiounis commented on src/java.base/share/conf/security/java.security
> +RestrictedSecurity.OpenJCEPlusFIPS.FIPS140-3.desc.hash = SHA256:bea1b7da967ac27720b7bc439ccd2d4250ebe783a6919a8e7047e6a6b862a116
Thanks for catching that.

2024-10-07 17:14 UTC, keithc-ca commented
Jenkins test sanity alinux jdk11

2024-10-07 21:17 UTC, keithc-ca approved these changes

2024-10-07 21:17 UTC, merged